edition = "2021"
group_imports = "One"
hex_literal_case = "Lower"
imports_granularity = "Item"
max_width = 75
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
spaces_around_ranges = true
tab_spaces = 2
trailing_semicolon = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
style_edition = "2024"
